### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by jkantner** [ChrisCavs/t-writer.js#1]
I did `npm install t-writer.js --save` to get the t-writer.js folder, dragged it to my directory, then tried the following code:

```
<body>
<script src="t-writer.js/dist/t-writer.js"></script>
<script>
import Typewriter from 't-writer.js';

const target = document.querySelector('body');
const writer = new Typewriter(target, {
  loop: true,
  typeColor: "red"
});

writer
	.type("Type something")
	.rest(500)
	.type("Type something again")
	.start();
</script>
</body>
```

I get the error `SyntaxError: Unexpected identifier 'Typewriter'. import call expects exactly one argument.` How do I fix this?

**Comment by ChrisCavs** [comment]
It's advised that you use a bundler so that you can import ES6 modules.  To import typewriter as you've outlined above, you would need to add `type="module"` to the script tag.  However, that will be prevented by CORS policy.

**Comment by jkantner** [comment]
I’m trying this out offline in `file:///…` and didn’t get any cross-origin error. When I added `"type=module"` though, then I got `TypeError: undefined is not an object (evaluating 'global['t-writer'] = factory()')`. Is there a more detailed procedure I could follow?

**Comment by ChrisCavs** [comment]
I would suggest using a bundler like [Webpack](https://webpack.js.org/), instead of pulling the module out of the node modules folder and trying to hack it.  They have a good demo on their page about how to get started with it. 

Once you have webpack running, the install instructions provided will work just fine.

**Comment by ChrisCavs** [comment]
I'm glad!  I hope you enjoy your new setup.  Using bundlers is a great thing to know when building web applications/sites, especially if you're using the latest tooling such as React.

**Comment by TechbyPanda** [comment]
import Typewriter from 't-writer.js'
when i am importing it is not showing error counld not find module

**Comment by anand-instrive** [comment]
https://snyk.io/advisor/npm-package/angular-typewriter-effect

**Comment by anand-instrive** [comment]
use this above link to install
