### ISSUE TITLE
Enhancement: accommodate html tags

### ISSUE THREAD

**Issue by eranmiller** [ChrisCavs/t-writer.js#5]
Hi Chris,
**Thank you for t-writer**, it's a fun visual enhancement unencumbered by frivolous bells and whistles.

If you're still actively developing this code, there is functionality I hope you will consider accommodating html tags (e.g. `<br>`, `<strong>`, `<em>`, etc... ) in the type method.

```
writer
.type('line 1<br>')
.type('<strong class="has-text-primary">line</strong> 2')
.type('line <em>three</em>')
.remove(3)
.type('<strong>four</strong>')
```
Initial output:
line 1
**line** 2
line _three_

Output after remove:
line 1
**line** 2
line **four**

Today, tags added to the text, always display the html opening tag `<` prior to rendering the completed tag, even with typeSpeed set to 0.  Similarly, when removing, the `<` always appears before being erased.  With this enhancement, when adding/removing tags, html tags will never appear on screen.

To minimize effects to existing user setups:
**.type** would add html tags as if they are 1 character long (i.e. `<br>` and `<strong class="has-text-primary">` would both generate on screen at the same speed.
**.remove** would remove html tags as if they are 1 character long (i.e. `<strong class="has-text-primary">` and `</strong>` would both be removed at the same speed.

That way text with and without HTML would type and remove at nearly an indiscernible difference.

Thank you in advance for your consideration and contributions to date.

**Comment by ChrisCavs** [comment]
Hey Eran, thanks for opening this.

My opinion on the matter is that html tags aren't necessary to accomplish what you set out to do in the example.  Instead, just create 3 typewriters (one on each line), and use the async callbacks provided in the API to synchronize them together.

Additionally, you can change class on the span element that contains the text (via the API), and incorporate bold text, etc.
